### ISSUE TITLE
16.5.1 no framerate switching Firestick gen2

### ISSUE THREAD

**Issue by HDGuy** [koying/SPMC#580]
Title says all. Not sure if framerate switching is supposed to work on the firestick, but it doesn't.

Also, any possibility of HEVC 1080p/24/30 hardware support? The Gen2 stick supports it.

**Comment by koying** [comment]
Fixed in 16.5.2

**Comment by HDGuy** [comment]
Not fixed for me at least. First thing I did was test it and it didn't switch. Works fine on my Shield TV, still doesn't switch on my TV Stick gen2. Stuck at default frame rate.

Oh, I did test HEVC support on the gen2 and it uses HW decoding just fine.:)

**Comment by koying** [comment]
Log Welcome.
BTW, what do you expect it to switch to? The Stick v1 didn't have 24p, if that's what you expected. No clue about the v2.

**Comment by HDGuy** [comment]
You can switch refresh rates on the Stick (both Gen1 and Gen2) by holding rewind and UP on the directional pads for 10 seconds.  24p is supported on both sticks.
