### ISSUE TITLE
Video Playback Stops Then Skips  16.6 - Was No Problem In 16.5

### ISSUE THREAD

**Issue by BluegrassPicker** [koying/SPMC#841]
Currently using SPMC 16.6 on Xiaomi MI Android Box

I am playing DVD video files from folders in standard DVD format from USB drive connected to Xiaomi MI Android box.

Periodically a video will pause for about three seconds and then it will jump forward and resume playing, but bypassing the section of the video that would have been shown during that period of time.  This seems to be occurring in the middle of a VOB segment, not at the end of the file.

This was not an issue with SPMC 16.5 and just began recently when SPMC auto-updated on my system.

Interestingly, when playing the videos by executing the VIDEO_TS.IFO file,  if I disable hardware acceleration first in the settings, the playback will randomly pause as described above, but when I play the videos by executing the VTS_01_0.VOB or other VOB files individually, the playback works normally - no stoppage - until it reaches the end of the file and then playback stops (I probably need to enable the "play next file" setting, but that's probably a separate issue.  

I can easily replicate the problem by re-executing the DVD VIDEO_TS.IFO file and then resuming play at the exact same position prior to the stoppage and then it will stop at the same place, every time.....  The stoppage seems to occur with any DVD file that I choose.

I have changed the auto refresh rate settings to the various choices and none seems to solve this problem.

I do not have the problem in Kodi 17.1 and I have the settings enabled in a similar manner in both programs, although Kodi has a setting for buffering which I have set to 3 and SPMC has no such setting for buffering available that I could find.  Additionally, Kodi does not have options to disable acceleration like SPMC does that I could find.

Does anyone have any suggestions?   I very much prefer SPMC since video playback seems to be more fluid, but the stoppage is a definite problem for me.

Thanks in advance.

Bluegrass Picker

**Comment by BluegrassPicker** [comment]
By the way, I'd like to extend my thanks for the efforts that have gone into SPMC.  The hard work is very much appreciated and is not taken lightly.

Cheers
Bluegrass Picker

**Comment by cesarious** [comment]
+1 here. I've go the same issue/same symptoms. 

Tried all 16.6 versions available for download. Indeed it was an issue not present before. Only alternative so far seems to be a to roll back, but it does not accept to just install a previous version. In my case I'm using SPMC on a Shield TV still on firmware v3.2.

Any idea is welcome. Thanks!.

**Comment by cesarious** [comment]
Last night tried to clean install aarch64 versions from current 16.6 to 16.5.82/81/80 to validate that the last version where DVD files are properly playback is SPMC-16.5.5-spmc-972797d-aarch64.apk 

DVD video-audio is properly playback until you reach 5 seconds the end of the chapter. Suddenly image and sound freezes and next chapter starts. Same is repeated when each chapter is reaching the end.

In a music video this is clearly seen. In a movie, you may think it is random.

Again issue is present when you start the DVD by a .IFO file (to have access to menues). .VOB works fine, but you loose chapters and continuous playback between different .VOB files.

Hopefully this feedback will help in troubleshooting.

Thanks for the hard work!

**Comment by BluegrassPicker** [comment]
I uninstalled 16.6 and installed 16.5.5 and video now plays properly without stopping or skipping and plays smooth.   

When an update is released I'll install the new release and test for the condition at that time.  

Thanks koying / SPMC

**Comment by freeducky** [comment]
I'm seeing this as well with an NVIDIA Shield TV (and a Nexus 7 2013). Doesn't happen with Kodi (17.1), didn't happen with earlier versions of SPMC on the same files. Happens immediately after installing from Play store, no customization other than MySQL connection (checked current SPMC and Kodi).

To describe the problem in more detail: it's only happening during DVD playback (not Blu-Ray), and the problem is that playback "skips" right before every chapter start (in my case, about ~9 seconds). All my DVDs are playing from .ISO images over NFS. So the behavior is that around 9 seconds before the end of every DVD chapter, playback freezes for a second or so, then playback resumes at the beginning of the next chapter. This happens with every chapter, and it doesn't matter whether you start playback at the beginning or move around to any point in the movie.

**Comment by Camsti** [comment]
I have the same problem, which is very very annoying.
I am using SPMC on Sony Android TV.
I will try to uninstall 16.6 and install 16.5 tomorrow.

Edit: Installed 16.5 and it works like a charm! Clearly an issue with 16.6!

**Comment by BluegrassPicker** [comment]
I had to disable the wifi adapter on my MI box after installing 16.5
(sideloaded via apk).  With wifi enabled SPMC would automatically update
to 16.6 and set all of my settings to default.  This happened several times
and I finally killed the wifi to prevent future updates until the problem
with skipping is resolved in a future release...

**Comment by shavanni** [comment]
Has this been fixed in 16.7?

**Comment by freeducky** [comment]
Also still a problem in 16.7. (As expected, given the 16.7 change log.)

**Comment by DorsetSteve** [comment]
I'm not sure if this adds a great deal, but I 'rolled back' to 16.5 on my Shield and there was no issue with the playback jumps on iso files, but there was an issue with audio passthrough of DTS-HD audio... All I got was a staccato burst a couple of times a second. All settings were same as I used in 16.6.  I reverted to 16.6 as I would rather have the skipped playback than no passthrough.

**Comment by wrxtasy** [comment]
The reliable setup for SD - DVD, .vob ( 480/576 mpeg2) files playback with SPMC:

Settings > Video Acceleration > (hardware) Accelerate MPEG2 > HD and Up 
(HD = 720 or greater resolution)

Then play a DVD and go into the OSD > Video Settings Menu:
http://kodi.wiki/view/video_playback#OSD_video_settings

Video Settings > Deinterlace Method > select Yadif or Yadif (2X) - depends which one gives smooth video playback. 
Yadif(2x) will produce higher quality deinterlacing for any Interlaced DVD playback.

Hardware with a weak CPU's like Sony/Philips TV's will need to leave Deinterlace Method in Auto or may need even to select Software Blend.

Then Set as default for all Media (down the bottom) 

SPMC will then Auto - ffmpeg2 Software decode and Software deinterlace SD mpeg2 / DVD's / .VOB's and bypass any problematic Hardware decoding for that combo.

**Comment by shavanni** [comment]
Hi wrxtasy. 

I already had the configuration you described. I'm still getting the video skipping a few seconds before the DVD chapter change. Problem appears to be SPMC 16.6 as kodi 17 does not have this issue.

**Comment by cesarious** [comment]
Quick update on my particular case (Shield TV 2015 still on firmware 3.2). Tried Kodi 17.3 and it is working  as reliable as SPMC 16.5. Almost caveat on 17.3 is that sometimes the movie file do not seem to start, and is you seek 10 sec ahead or back the issue is solved.

But all passthrough and dvd i tried, worked flawlessly. 

I'm keeping both versions installed just in case.

Regards.

**Comment by dproffitt** [comment]
I have tried all that is suggested here and nothing has helped. I hope I can provide more information that could point others in the right direction. Background - I am running SPMC 16.7.1, and have not tried a rollback to 16.5. I have this version installed on three devices, 2 Android STBs of different manufacturers and one tablet (Pixel C). The files that skip are DVD files on my NAS. The skips are consistent so I narrowed my trials to a single occurrence in a movie that always skipped at 16:40. It skips to 16:50. It starts exhibiting problems at 16:30 when the seconds counter stutters and goes up and down without any movie video or audio problems until it stops at 16:40 and skips ahead to 16:50. I would guess this happens on all movies at least 15 to 20 times. I finally tried to install Kodi 17.4 on the STBs to see if it helped and it did not have this problem at all. If I liked the Kodi skins as much as I like SPMC it would be an easy decision, but I don't. As it is I hope somebody tackles this. Thanks.
